export const TYPOGRAPHY = {
  small: 'text-m-sm sm:text-t-sm md:text-d-sm leading-m-sm sm:leading-t-sm md:leading-d-sm',
  base: 'text-m-base sm:text-t-base md:text-d-base leading-m-base sm:leading-t-base md:leading-d-base',
  large: 'text-m-lg sm:text-t-lg md:text-d-lg leading-m-lg sm:leading-t-lg md:leading-d-lg',
  'inherit': 'text-inherit leading-inherit',
};

export const ALIGN = {
  start: 'text-start',
  end: 'text-end',
  right: 'text-right',
  left: 'text-left',
  center: 'text-center',
  justify: 'text-justify',
  inherit: 'text-right',
};

export const TYPE = {
  light: 'font-light',
  regular: 'font-normal',
  medium: 'font-medium',
  bold: 'font-bold',
};

export const COLOR = {
  inherit: 'text-inherit',
  primary: 'text-primary',
  secondary: 'text-secondary',
  tertiary: 'text-tertiary',
  control: 'text-control',
  success: 'text-success',
  info: 'text-info',
  warning: 'text-warning',
  danger: 'text-danger',
  black: 'text-black',
  white: 'text-white',
  'grey.light': 'text-grey-light',
  'grey': 'text-grey',
  'grey.dark': 'text-grey-dark',
  purple: 'text-purple-500',
  slate: 'text-slate-500',
  gray: 'text-gray-500',
  zinc: 'text-zinc-500',
  neutral: 'text-neutral-500',
  stone: 'text-stone-500',
  red: 'text-red-500',
  orange: 'text-orange-500',
  amber: 'text-amber-500',
  yellow: 'text-yellow-500',
  lime: 'text-lime-500',
  green: 'text-green-500',
  emerald: 'text-emerald-500',
  teal: 'text-teal-500',
  cyan: 'text-cyan-500',
  sky: 'text-sky-500',
  blue: 'text-blue-500',
  indigo: 'text-indigo-500',
  violet: 'text-violet-500',
  fuchsia: 'text-fuchsia-500',
  pink: 'text-pink-500',
  rose: 'text-rose-500',
};
