export const COLORS = {
  primary: 'text-primary',
  danger: 'text-danger',
  warning: 'text-warning',
  secondary: 'text-secondary',
  control: 'text-control',
  tertiary: 'text-tertiary',
  success: 'text-success',
  info: 'text-info',
  inherit: 'text-inherit',
  slate: 'text-slate-500',
  gray: 'text-gray-500',
  zinc: 'text-zinc-500',
  neutral: 'text-neutral-500',
  stone: 'text-stone-500',
  red: 'text-red-500',
  orange: 'text-orange-500',
  amber: 'text-amber-500',
  yellow: 'text-yellow-500',
  lime: 'text-lime-500',
  green: 'text-green-500',
  emerald: 'text-emerald-500',
  teal: 'text-teal-500',
  cyan: 'text-cyan-500',
  sky: 'text-sky-500',
  blue: 'text-blue-500',
  indigo: 'text-indigo-500',
  violet: 'text-violet-500',
  purple: 'text-purple-500',
  fuchsia: 'text-fuchsia-500',
  pink: 'text-pink-500',
  rose: 'text-rose-500',
};

export const SIZES = {
  tiny: 'w-4 h-4',
  small: 'w-5 h-5',
  medium: 'w-6 h-6',
  large: 'w-8 h-8 ',
  huge: 'w-10 h-10',
};
